insert into penalty_templates (title, description,penalty_type_id, duration) values ('nat', 'Tworzenie podsieci w sieci (NAT). Skontaktuj się ze swoim administratorem lokalnym w celu złożenia wyjaśnień. (Creating subnetworks (NAT). Please contact your local network administrator for explanation)', 1,30);
insert into penalty_templates (title, description,penalty_type_id, duration) values ('podszywanie', 'Podszywanie się pod innych użytkowników w sieci. (Impersonating other users in the SKOS network)', 1,30);
insert into penalty_templates (title, description,penalty_type_id, duration) values ('upload', 'Przekroczenie uploadu. Limituj ruch wychodzący poza SKOS do 60kB/s w godzinach od 10 rano do 1 w nocy, w przeciwnym przypadku zostaniesz ukarany odcięciem od usługi na 1 miesiąc. (Too high upload. You should limit your outgoing traffic outside the SKOS network to 60kb/s between 10:00 A.M. - 1:00 A.M otherwise we cut Your access to the network for 1 month)', 1,7);
insert into penalty_templates (title, description,penalty_type_id, duration) values ('upload recydywa', 'Niezastosowanie się do wcześniejszych ostrzeżeń odnośnie ograniczenia uploadu. (Not following to earlier requests about limiting the upload)', 1,30);
insert into penalty_templates (title, description,penalty_type_id, duration) values ('wirusy', 'Twój komputer jest najprawdopodobniej zawirusowany. Usuń problem. (Your computer is probably infected by a virus. Please remove that problem)', 1,7);
insert into penalty_templates (title, description,penalty_type_id, duration) values ('wirusy recydywa', 'Komputer zawirusowany ponownie. Usuń problem. (Your computer is infected by a virus again. Remove that problem)', 1,30);
insert into penalty_templates (title, description,penalty_type_id, duration) values ('piraty', 'Udostępnianie pirackich kopii materiałów chronionych prawem autorskim. (Sharing unauthoriezed copies of the materials protected by author''s law.)', 1,30);
insert into penalty_templates (title, description,penalty_type_id, duration) values ('piraty recydywa', 'Ponowne udostępnianie pirackich kopii materiałów chronionych prawem autorskim. (Sharing unauthoriezed copies of the materials protected by author''s law again.)', 1,5000);


